
# A string used to distinguish different Supabase projects on the same host. Defaults to the
# working directory name when running `supabase init`.
project_id = "dkdjnstcsmwsowlbvvzq"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "10MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
uri_allow_list = ["https://localhost:3000"]
additional_redirect_urls = ["https://localhost:3000"]

[analytics]
enabled = false
port = 54327
vector_port = 54328

[functions]
[functions.generate-pdf]
verify_jwt = true
