
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/integrations/supabase/types';
// Type augmentation is automatically picked up via tsconfig.json includes

const SUPABASE_URL = "https://dkdjnstcsmwsowlbvvzq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRrZGpuc3Rjc213c293bGJ2dnpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxODI1ODUsImV4cCI6MjA2MDc1ODU4NX0.aqbFyo2-eV80yhSBod2O0PS5v3bD3TJ3d3B-cLvjS1g";
export const SUPABASE_FUNCTIONS_PATH = `${SUPABASE_URL}/functions/v1`;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
export { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY };
